# Name of this app
service: fizzy
image: sdod/fizzy


#-- About your deployment --#

# Where to deploy fizzy
servers:
  web:
    - 10.111.129.16

# How you connect to your server
ssh:
  user: ubuntu  # If you use a different username to SSH to your server, specify it here

# Automatic SSL
proxy:
  ssl: false
  hosts:
    - fizzy.sdod.io
    - 10.111.129.16

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - MAILGUN_DOMAIN
    - MAILGUN_API_KEY
  clear:
    BASE_URL: https://fizzy.example.com # The public URL of your Fizzy instance
    MAILER_FROM_ADDRESS: support@example.com # The email "from" address that Fizzy sends email from
    SMTP_ADDRESS: mail.example.com # The SMTP server you'll use to send email
    MULTI_TENANT: false # Set to true to allow multiple accounts to sign up
    SOLID_QUEUE_IN_PUMA: true # Run background jobs in the app container


#-- General configuration --#

# Use a local registry to deploy
registry:
  # Alternatives: hub.docker.com / registry.digitalocean.com / ghcr.io / ...
  # server: localhost:5555

  # Artifactory
  server: sdod-fizzy-docker-prod-local.artifactory.sie.sony.com
  username: pasanchez

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch:
  - amd64
  - arm64
